version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt update
            sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo npm install @neuralegion/nexploit-cli -g --unsafe-perm=true || true
      - setup_remote_docker
      - run:
         name: Save eniroment variables
         command: |
            printf "NEXPLOIT_TOKEN=$NEXPLOIT_TOKEN\nREPEATER=$REPEATER\n" > .env
            cat .env
      - run:
         name: Docker-Compose
         command: |
            echo $NEXPLOIT_TOKEN
            echo $REPEATER
            docker-compose --env-file=.env up -d
            docker-compose config
      - run:
          name: Starting Nexploit scan 🏁
          command: >
              echo export SCAN_ID=$(nexploit-cli scan:run --token $NEXPLOIT_TOKEN
              --repeater $REPEATER
              --name "CIRCLECI TEST"
              --crawler http://juiceshop.local:3000
              --smart) >> "$BASH_ENV"
      - run: 
          name: Get the output scan url 🔗
          command: |
            printf "Scan was started with ID https://nexploit.app/scans/${SCAN_ID}"
      - run:
          name: Waiting for issues ⏳
          command: >
              (nexploit-cli scan:polling
              --interval 30s
              --timeout 20m
              --token $NEXPLOIT_TOKEN
              --breakpoint medium_issue ${SCAN_ID})
      - run:
          name: Stop Scan 🛑
          when: on_fail
          command: |
              nexploit-cli scan:stop --token $NEXPLOIT_TOKEN ${SCAN_ID}